version: "3.9"
 
services:
  monitoring:
    build: .
    image: monitoring_v1            # builds and tags the image as monitoring_v1
    container_name: activity_monitoring
    ports:
      - "5002:5002"
    restart: always
    networks:
      - manufacturing_network
 
networks:
  manufacturing_network:
    external: true